### PR TITLE
Enable support for non-strings to be colorized by implicitly converti…

### PR DESCRIPTION
**Pull request by TheStranjer**
…ng them into strings first (or for enumerables, iterating over them)

I wrote this because it's annoying having to run `to_s` on everything in order to colorize a non-String, or having to iterate over every element in an Array, so it will implicitly colorize it or its elements. Just reject if you think this is a stupid or unworthwhile pursuit.

### CODE REVIEW

**Comment by jefflunt** [comment]
Extending `String`, while incredibly useful, I think is far enough. With the proposed change a programmer can do something like the below, but I'm not sure of the utility of it would be:

```ruby
require 'colorize'

hash = { a: 'A', b: 'B' }
hash.red                        # why support this?

f = File.new('/tmp/test.txt', 'w')
r.red                           # why support this?
```

My $0.02 is that I'd prefer an explicit conversion to a `String` first. I can maybe see an argument for things like `1_000_000.red`, but the existing PR extends `Object`, which pollutes ... well, everything.

**Comment by TheStranjer** [comment]
This PR is nearly a year old. I've been using my fork of this with it for a long time now.

**Comment by TheStranjer** [comment]
Also, by the time you're calling `#green`, `#cyan`, etc, you're very likely referring to the color anyway. I can't think of a lot of cases where you would want a method with any of these names other than colorization, to the point that having a terser approach baked in to the gem is better than not.

**Comment by jefflunt** [comment]
> This PR is nearly a year old.

Yeah, just happened to scan through the PRs today is all.

> I can't think of a lot of cases where you would want a method with any of these names other than colorization ...

Sure. I'm coming at it from the other angle: why add this to classes that have no use for it, when every descendent of `Object` already has `#to_s`? If I'm understanding where you're coming from, you like the brevity of it, i.e.:

```ruby
some_object.red       # you would prefer this
some_object.to_s.red  # rather than this
```

... in order to save the explicit conversion to the `String` class, correct?

I guess I just don't follow. OOP is about combining data with operations on that data. `#red` is not an operation on a generic `Object`, it's only a valid operation on a `String`, which is why it's currently defined on `String`.

Like you mentioned, you have a fork, so yeah you're free to do whatever you like on the fork. But the PR is to make that the default behavior for everyone, so I'm trying to think not just, "What harm does it do?" but also "What's the use case for it?"

Thanks for the response. The PR was thought-provoking.

**Comment by TheStranjer** [comment]
The argument for putting it in Object is that it opens the doors to running it on other things without an explicit conversion to String. The argument against it is that there might be some other class that also uses these method names and that would be disruptive. Because in my reality I found a lot of cases where I wanted to colorize a number or an array, but no examples of other classes wanting those method names, I made the judgment call that the terseness offered outweighed the potential for danger.

But a judgment call it is, and it's sounding like you're inclined to go the other way.

**Comment by jefflunt** [comment]
That's my opinion, yeah, but I wanted to hear you out.

I'm not necessarily against a more focused extension (`Integer`/`Float`, maybe `Array` and `Hash`) - things that have a more clear-cut case for printing to a screen all the time.

Another possibility might be (I haven't thought this through much TBH) to allow configuring the gem to programmatically extend a list of classes that the user specifies (i.e. _you_ could put `Object` in there for your use cases, but by default the gem would still only extend `String`, rather than changing `Object` to the default extension point).

Let me see if the PRs I submitted today go anywhere (#73  and #72) over the next few months. I don't know @fazibear's level of motivation to maintain this gem any further since (a) it's a really simple gem, (b) even without maintenance it's continued to work without issues for years, and (c) I think he might have moved on to focusing on Elixir more than Ruby.

Anyway - thanks again for taking the time to explain your point of view.

**Comment by TheStranjer** [comment]
My intention was to leave it on Object until someone complained and then limit it somehow when and if someone ever did. That someone might be me.

**Comment by jefflunt** [comment]
LOL - fair. I'll throw my hat in the ring as someone who's very lightly complaining. That said, I'd be happy to make a contribution that makes your use case easy, without changing the default behavior.

The reason I hesitate isn't just because I don't want things to change (being conservative towards change for no other reason isn't helpful). I use `colorize` in some production projects, and I don't want the entire object space to have these all methods. The gem is sufficiently used around the web (73M+ downloads and counting) that I think the potential for unintended consequences is quite high. I might feel different if this gem was earlier in its life and we didn't have a bunch of people who implicitly depend on the current behavior and scope.

Philosophically I'm more of the mind of, "Since this is already widely used, let's take a little more time to consider possible effects, rather than throwing caution to the wind and apologize later." I get that people can just rollback their gem version, but in the case of this gem a small change can actually affect a lot of people.

**Comment by jefflunt** [comment]
And just in case it's not clear, I'm just a normal user of `colorize` like you - I don't have any special permissions on this repo.

**Comment by TheStranjer** [comment]
Nah, I know what I'm doing, I just also know that things can be undone on a whim. So when you find another gem that uses `#red` or `#cyan` or whatever, and there's a real case of them overlapping, then I'll change it on my branch.

**Comment by jefflunt** [comment]
> So when you find another gem that uses #red or #cyan or whatever, and there's a real case of them overlapping, then I'll change it on my branch.

This still doesn't seem like a compelling reason to change the default extension class to `Object`, for all users of the gem.

**Comment by TheStranjer** [comment]
There being a lack of argument against it, and it being convenient for it to be so, seems compelling to me. The very specific case where `Object#red` is up for dispute is if some other gem wants to have `Object#red` as well, in which case it becomes a race condition as to which one comes first. See, if some descendant of `Object` defines `#red` then that definition overrides it. It doesn't matter the order in which they're declared, either:

```ruby
3.0.0 :001 > class String
3.0.0 :002 >   def red
3.0.0 :003 >     "TEST"
3.0.0 :004 >   end
3.0.0 :005 > end
 => :red 
3.0.0 :006 > class Object
3.0.0 :007 >   def red
3.0.0 :008 >     "ELSE"
3.0.0 :009 >   end
3.0.0 :010 > end
 => :red 
3.0.0 :011 > String.new.red
 => "TEST" 
3.0.0 :012 > Object.new.red
 => "ELSE" 
```

And:

```ruby
3.0.0 :001 > class Object
3.0.0 :002 >   def red
3.0.0 :003 >     "ELSE"
3.0.0 :004 >   end
3.0.0 :005 > end
 => :red 
3.0.0 :006 > class String
3.0.0 :007 >   def red
3.0.0 :008 >     "TEST"
3.0.0 :009 >   end
3.0.0 :010 > end
 => :red 
3.0.0 :011 > String.new.red
 => "TEST" 
3.0.0 :012 > Object.new.red
 => "ELSE" 
```

I understand wanting to be cautious about this sort of thing, but on the other hand, the fundamentally mutable nature of code has convinced me that this sort of thing isn't a problem until it is, and when it is a problem it's not hard to change it.

**Comment by jefflunt** [comment]
I think this is going to wind up being a moot point because I don't see activity from the project owner.

**Comment by fazibear** [comment]
Hey! Thanks for your contribution. Read all this thread. I think applying all generated methods to object it's too much. If you want you can always create your own `colorize-object` gem, use `colorize` as dependency and implement all of those things there :)

**Pull request closed without merging**
